name: backend
description: An empty conduit application.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  conduit: ^3.2.0
  conduit_open_api: ^3.2.10

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^3.2.0
